pipelines:
  authorizer: # definition of mypipe1 pipeline
    group: lambda # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${authorizer[:8]}"
    materials:
      authorizer: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: https://github.com/C0k3/session
        branch: development
        whitelist:
        - lambda_functions/authorizer/**/*.*
        - pipelines.gocd.yaml
    stages:
      - unit-testing:
          clean_workspace: true
          jobs:
            run:
              environment_variables:
                NODE_ENV: development
              artifacts:
              - test:
                  source: test-results.xml
                  destination: test-reports/
              # tabs:
              #   report: test-reports/index.html
              tasks: # ordered list of tasks to execute in job csharp
              - script: |
                  ls -al
                  npm install
                  node_modules/.bin/mocha-webpack
